name: ⬇️ Download Locale from Crowdin

on:
  workflow_dispatch:
  workflow_run:
    workflows: ['Upload EN strings to Crowdin']
    types:
      - completed
  schedule:
    # Runs "twice a day" (see https://crontab.guru)
    - cron: '0 0,12 * * *'

jobs:
  synchronize-with-crowdin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: crowdin action
        uses: crowdin/github-action@v2
        with:
          upload_sources: false
          upload_translations: false
          download_translations: true
          localization_branch_name: l10n_crowdin_translations
          create_pull_request: true
          pull_request_title: 'Update Translations'
          pull_request_body: 'Update translations'
          pull_request_base_branch_name: 'main'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
